In [1]:
import pandas as pd
import joblib
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
X_test = pd.read_pickle("../data/processed/X_test.pkl")
y_test = pd.read_pickle("../data/processed/y_test.pkl")

model = joblib.load("../models/best_model.pkl")

In [3]:
y_pred = model.predict(X_test)

In [4]:
error_df = X_test.copy()
error_df["actual"] = y_test.values
error_df["predicted"] = y_pred

error_df["error_type"] = "Correct"
error_df.loc[
    (error_df["actual"] == 0) & (error_df["predicted"] == 1),
    "error_type"
] = "False Positive"

error_df.loc[
    (error_df["actual"] == 1) & (error_df["predicted"] == 0),
    "error_type"
] = "False Negative"

error_df["error_type"].value_counts()

error_type
Correct           146
False Negative     18
False Positive     15
Name: count, dtype: int64

In [8]:
# the people whose data is wrong
error_df[error_df["error_type"] != "Correct"][
    ["IsFemale", "AgeFilled", "FareFilled", "FamilySize", "error_type"]
].head(10)

     IsFemale  AgeFilled  FareFilled  FamilySize      error_type
621 -0.737695   0.971260    0.409741    0.059160  False Negative
447 -0.737695   0.356462   -0.113846   -0.560975  False Negative
673 -0.737695   0.125912   -0.386671   -0.560975  False Negative
396  1.355574   0.125912   -0.490280   -0.560975  False Positive
235  1.355574  -0.104637   -0.496405   -0.560975  False Positive
204 -0.737695  -0.873136   -0.486337   -0.560975  False Negative
23  -0.737695  -0.104637    0.066360   -0.560975  False Negative
362  1.355574   1.201810   -0.357391    0.059160  False Positive
772  1.355574   2.124008   -0.437007   -0.560975  False Positive
312  1.355574  -0.258337   -0.124920    0.679295  False Positive

In [6]:
# people who survived but model predicted they died
error_df[error_df["error_type"] == "False Negative"][
    ["IsFemale", "AgeFilled", "FareFilled", "FamilySize"]
].head(10)

     IsFemale  AgeFilled  FareFilled  FamilySize
621 -0.737695   0.971260    0.409741    0.059160
447 -0.737695   0.356462   -0.113846   -0.560975
673 -0.737695   0.125912   -0.386671   -0.560975
204 -0.737695  -0.873136   -0.486337   -0.560975
23  -0.737695  -0.104637    0.066360   -0.560975
889 -0.737695  -0.258337   -0.044381   -0.560975
712 -0.737695   1.432359    0.398582    0.059160
338 -0.737695   1.201810   -0.486337   -0.560975
286 -0.737695   0.049062   -0.457142   -0.560975
209 -0.737695   0.817561   -0.024246   -0.560975

In [7]:
# people who died but model predicted they survived
error_df[error_df["error_type"] == "False Positive"][
    ["IsFemale", "AgeFilled", "FareFilled", "FamilySize"]
].head(10)

     IsFemale  AgeFilled  FareFilled  FamilySize
396  1.355574   0.125912   -0.490280   -0.560975
235  1.355574  -0.104637   -0.496405   -0.560975
362  1.355574   1.201810   -0.357391    0.059160
772  1.355574   2.124008   -0.437007   -0.560975
312  1.355574  -0.258337   -0.124920    0.679295
767  1.355574   0.087487   -0.492378   -0.560975
357  1.355574   0.663861   -0.386671   -0.560975
254  1.355574   0.894411   -0.241449    0.679295
527 -0.737695  -0.104637    3.817033   -0.560975
139 -0.737695  -0.412037    0.946246   -0.560975

In [ ]:
cm = confusion_matrix(y_test, y_pred)

plt.figure()
sns.heatmap(cm, annot=True, fmt="d")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()